import Link from "next/link";
import Image from "next/image";
import { site } from "@/lib/site-config";

const links = [ ["Formations", "/formations"], ["Méthode", "/methode-pedagogique"], ["À propos", "/a-propos"], ["Avis", "/avis"], ["FAQ", "/faq"] ];
export function Header() { return <header className="header"><Link href="/" className="brand" aria-label="Konform’up — accueil"><Image src="/konformup-logo.png" width={130} height={98} priority alt="Logo Konform’up"/></Link><nav aria-label="Navigation principale">{links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><Link className="button button-small" href="/demande-devis">Demander un devis</Link></header>; }
function PhoneIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 2.8 9.4 2l1.8 4.5-2 1.5c1 2.1 2.7 3.8 4.8 4.8l1.5-2 4.5 1.8-.8 2.8a2.8 2.8 0 0 1-3.1 2C8.9 16.5 7.5 15.1 6.6 8.1a2.8 2.8 0 0 1 0-5.3Z"/></svg>}
function MailIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>}
function InstagramIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>}
function LinkedInIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 10v6M8 7.2v.1M12 16v-3.3a2.6 2.6 0 0 1 5.2 0V16M12 10v6"/></svg>}
export function Footer() { return <footer className="footer"><div className="footer-grid"><div><p className="footer-brand">Konform’up</p><p>Prévention, hygiène et pratiques numériques concrètes pour les entreprises.</p></div><div><p className="eyebrow">Explorer</p><Link href="/formations">Formations</Link><Link href="/methode-pedagogique">Méthode</Link><Link href="/demande-devis">Demander un devis</Link></div><div><p className="eyebrow">Nous joindre</p><a className="contact-link" href={`mailto:${site.contact.email}`}><MailIcon/><span>{site.contact.email}</span></a>{site.contact.phone ? <a className="contact-link" href={`tel:${site.contact.phone.replace(/\s/g, "")}`}><PhoneIcon/><span>{site.contact.phone}</span></a> : null}</div><div><p className="eyebrow">Suivre Konform’up</p><div className="social-links">{site.social.instagram ? <a href={site.social.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram Konform’up (nouvel onglet)"><InstagramIcon/></a> : null}{site.social.linkedin ? <a href={site.social.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn de Karine Vannucci (nouvel onglet)"><LinkedInIcon/></a> : null}</div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Konform’up. Tous droits réservés.</span><span><Link href="/mentions-legales">Mentions légales</Link><Link href="/politique-confidentialite">Confidentialité</Link></span></div></footer>; }
export function Page({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><Footer/></>; }
export function Breadcrumb({ current }: { current: string }) { return <nav className="breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span aria-hidden>/</span><span>{current}</span></nav>; }
