import Link from "next/link";
import Image from "next/image";
import { site } from "@/lib/site-config";

const links = [ ["Formations", "/formations"], ["Méthode", "/methode-pedagogique"], ["À propos", "/a-propos"], ["Avis", "/avis"], ["FAQ", "/faq"] ];
export function Header() { return <header className="header"><Link href="/" className="brand" aria-label="Konform’up — accueil"><Image src="/konformup-logo.png" width={130} height={98} priority alt="Logo Konform’up"/></Link><nav aria-label="Navigation principale">{links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><Link className="button button-small" href="/demande-devis">Demander un devis</Link></header>; }
export function Footer() { return <footer className="footer"><div><p className="footer-brand">Konform’up</p><p>Prévention, hygiène et pratiques numériques concrètes pour les entreprises.</p></div><div><p className="eyebrow">Naviguer</p><Link href="/formations">Formations</Link><Link href="/contact">Contact</Link><Link href="/demande-devis">Demander un devis</Link></div><div><p className="eyebrow">Informations</p><Link href="/mentions-legales">Mentions légales</Link><Link href="/politique-confidentialite">Confidentialité</Link>{site.social.instagram ? <a href={site.social.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram Konform’up (nouvel onglet)">Instagram ↗</a> : null}{site.social.facebook ? <a href={site.social.facebook} target="_blank" rel="noopener noreferrer" aria-label="Facebook Konform’up (nouvel onglet)">Facebook ↗</a> : null}</div><p className="footer-bottom">© {new Date().getFullYear()} Konform’up. Tous droits réservés.</p></footer>; }
export function Page({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><Footer/></>; }
export function Breadcrumb({ current }: { current: string }) { return <nav className="breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span aria-hidden>/</span><span>{current}</span></nav>; }
