import Link from "next/link";
import Image from "next/image";
import { site } from "@/lib/site-config";

const links = [ ["Formations", "/formations"], ["Méthode", "/methode-pedagogique"], ["À propos", "/a-propos"], ["Avis", "/avis"], ["FAQ", "/faq"] ];
export function Header() { return <header className="header"><Link href="/" className="brand" aria-label="Konform’up — accueil"><Image src="/konformup-logo.png" width={130} height={98} priority alt="Logo Konform’up"/></Link><nav aria-label="Navigation principale">{links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><Link className="button button-small" href="/demande-devis">Demander un devis</Link></header>; }
export function Footer() { return <footer className="footer"><div><p className="footer-brand">Konform’up</p><p>Prévention, hygiène et pratiques numériques concrètes pour les entreprises.</p></div><div><p className="eyebrow">Naviguer</p><Link href="/formations">Formations</Link><Link href="/contact">Contact</Link><Link href="/demande-devis">Demander un devis</Link></div><div><p className="eyebrow">Informations</p><Link href="/mentions-legales">Mentions légales</Link><Link href="/politique-confidentialite">Confidentialité</Link>{site.social.instagram ? <a href={site.social.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram Konform’up (nouvel onglet)">Instagram ↗</a> : null}{site.social.linkedin ? <a href={site.social.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn Konform’up (nouvel onglet)">LinkedIn ↗</a> : null}</div><div className="footer-contact"><p className="eyebrow">Nous contacter</p><a href={`mailto:${site.contact.email}`}>{site.contact.email}</a>{site.contact.phone ? <a href={`tel:${site.contact.phone.replace(/\s/g, "")}`}>{site.contact.phone}</a> : null}<div className="credential-logos"><Image src="/qualiopi-logo.png" alt="Qualiopi, processus certifié" width={152} height={76}/><Image src="/inrs-logo.svg" alt="INRS" width={86} height={40}/><Image src="/sst-formateur-logo.png" alt="Sauveteur secouriste du travail - niveau formateur" width={58} height={52}/></div><p className="credentials">Habilitation SST n° {site.credentials.sstHabilitation}</p></div><p className="footer-bottom">© {new Date().getFullYear()} Konform’up. Tous droits réservés.</p></footer>; }
export function Page({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><Footer/></>; }
export function Breadcrumb({ current }: { current: string }) { return <nav className="breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span aria-hidden>/</span><span>{current}</span></nav>; }
